services:
  jenkins-mongo:
    image: "mongo:latest"
    networks:
      - jenkins
  jenkins-s3:
    image: "minio/minio"
    networks:
      - jenkins
    ports:
      - "9001:9000"
      - "9200:9100"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "Passw0rd"
    command: server --address ":9000" --console-address ":9100" /data
  jenkins-bucket-creation:
    links:
      - "jenkins-s3:s3"
    image: minio/mc
    networks:
      - jenkins
    depends_on:
      - jenkins-s3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add s3 http://s3:9000 admin Passw0rd;
      /usr/bin/mc mb s3/panda-jenkins-bucket;
      /usr/bin/mc policy set public s3/panda-jenkins-bucket;
      exit 0;
      "
networks:
  jenkins:
    name: jenkins