version: '3.8'
services:
  app:
    image: steve763/photo-api:titanium-panda-6
    ports:
      - "3000:8080"
    links:
      - "mongo:panda-docker-mongo"
    networks:
      - portfolio
  mongo:
    image: "mongo:latest"
    networks:
      - portfolio
networks:
  titanium:
    name: portfolio